udemy/projects/univ-app/config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  get 'courses/new', to: 'courses#new'
  resources :courses, only: [:show]
  get 'about', to: 'pages#about'
  resources :students, except: [:destroy]
  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'
  post 'course_enroll', to: 'student_courses#create'
end

udemy/projects/univ-app/app/models/Course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :short_name, presence: true, length: { minimum: 3, maximum: 15 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  has_many :student_courses
  has_many :students, through: :student_courses
end

udemy/projects/univ-app/app/models/Student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  
  validates :email, presence: true, length: { maximum: 105 }, 
                          uniqueness: { case_sensitive: false },            
                          format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  has_many :student_courses
  has_many :courses, through: :student_courses
end

udemy/projects/univ-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

udemy/projects/univ-app/app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

udemy/projects/univ-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  before_action :require_user

  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:notice] = 'You should be logged in to perform that action'
      redirect_to login_path
    end
  end
end

udemy/projects/univ-app/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
  end
end

udemy/projects/univ-app/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action(:require_user , only: [:new, :create])

  def new
  end

  def create
    student = Student.find_by(email: params[:logins][:email].downcase)
    if student && student.authenticate(params[:logins][:password])
      session[:student_id] = student.id
      flash[:notice] = 'You have successfully logged in'
      redirect_to student
    else
      flash.now[:notice] = 'Something was wrong with you email authentification'
      render 'new'
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:notice] = 'You have successfully logged out'
    redirect_to root_path
  end
end

udemy/projects/univ-app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user

  def about
  end
end

udemy/projects/univ-app/app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
  def create
    course_to_add = Course.find(params[:course_id])
    unless current_user.courses.include?(course_to_add)
      StudentCourse.create(course: course_to_add, student: current_user)
      flash[:notice] = "You have successfully enrolled in #{course_to_add.name}"
      redirect_to current_user
    else
      flash[:notice] = 'Something was wrong with your enrollment'
      redirect_to root_path
    end
  end
end

udemy/projects/univ-app/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update]
  skip_before_action :require_user, only: [:new, :create]
  before_action :require_same_student, only: [:edit, :update]

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = "You have successfully signed up"
      redirect_to @student
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @student.update(student_params)
      flash[:notice] = 'You have successfully updates your profile'
      redirect_to @student
    else
      render 'edit'
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :password)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def require_same_student
    if current_user != @student
      flash[:notice] = 'You can only edit your own profile'
      redirect_to student_path(current_user)
    end
  end
end

udemy/projects/univ-app/app/helpers/application_helper.rb
module ApplicationHelper
  def session_link
    if (logged_in?)
      link_to 'Logout', logout_path, method: :delete
    else
      link_to 'Login', login_path
    end
  end
end

udemy/projects/univ-app/app/views/layouts/_footer.html.erb
<footer class="page-footer">
    <div class="container">
        <div class="row">
        <div class="col l6 s12">
            <h5 class="white-text">Tech University</h5>
            <p class="grey-text text-lighten-4">The future os development training</p>
        </div>
        <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Information</h5>
            <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
            </ul>
        </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
        © 2018 Tech University
        <a class="grey-text text-lighten-4 right" href="#!">About</a>
        </div>
    </div>
</footer>

udemy/projects/univ-app/app/views/layouts/_navigation.html.erb
<header>

    <!-- Dropdown Structure -->
    <ul id="dropdown1" class="dropdown-content">
        <li><%= session_link %></li>
        <% if logged_in? %>
            <li><%= link_to 'Profile', student_path(current_user) %></li>
        <% end %>
        <li><%= link_to 'New Course', courses_new_path %></li>
    </ul>
    <ul id="dropdown2" class="dropdown-content">
        <li><%= session_link %></li>
        <% if logged_in? %>
            <li><%= link_to 'Profile', student_path(current_user) %></li>
        <% end %>
        <li class="divider"></li>
        <li><a href="#!">three</a></li>
    </ul>
    <nav>
        <div class="container">
        <div class="nav-wrapper">
            <%= link_to 'Tech University', root_path, class: 'brand-logo right' %>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li><%= link_to 'Courses', root_path %></li>
            <% if logged_in? %>
                <li><%= link_to 'Students', students_path %></li>
            <% end %>
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
            </ul>

            <ul class="sidenav" id="mobile-demo">
            <li><%= link_to 'Courses', root_path %></li>
            <% if logged_in? %>
                <li><%= link_to 'Students', students_path %></li>
            <% end %>
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
            </ul>
        </div>
        </div>
    </nav>

    <% flash.each do |key, message| %>
        <div class="container">
            <div class="row sign-up-form">
                <div class="col s12 m12 l12">
                    <div class="card-panel red lighten-2" id="fade-out-target">
                        <span class="white-text">
                            <%= message %>
                        <span>
                    </div>
                </div>
            </div>
        </div>
    <% end %>

</header>

udemy/projects/univ-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech University</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/navigation' %>
  <body>  
    
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

  </body>
  <%= render 'layouts/footer' %>
</html>

udemy/projects/univ-app/app/views/pages/about.html.erb
<h1>About page</h1>