udemy/projects/alpha-blog/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

udemy/projects/alpha-blog/app/models/article.rb
class Article < ApplicationRecord  
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum: 6, maximal: 100}
    validates :description, presence: true, length: {minimum: 10, maximal: 300}
end

udemy/projects/alpha-blog/app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

udemy/projects/alpha-blog/app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

udemy/projects/alpha-blog/app/models/user.rb
class User < ApplicationRecord

    before_save { self.email = email.downcase}
    
    has_many :articles, dependent: :destroy

    validates :username, presence: true, 
            uniqueness: { case_sensitive: false }, length: {minimun: 3, maximum:25}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, 
            uniqueness: { case_sensitive: false }, length: { maximum: 105},
            format: {with: VALID_EMAIL_REGEX}

    has_secure_password
end

udemy/projects/alpha-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        return !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end
end

udemy/projects/alpha-blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, exept: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show ()
    end

    def index ()
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new ()
        # so the first time the page loads, it does not generate any error
        @article = Article.new()
    end

    def create ()
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article was created successfully"
            # redirect_to article_path(@article)
            redirect_to @article
        else
            render "new"
            # redirect_to new_article_path # no funciona porque al redireccionar se pierden los parametros
        end
    end

    def update ()
        if @article.update(article_params)
            flash[:notice] = "Article was updated successfully"
            redirect_to @article
        else
            render "edit"
        end
    end
 
    def edit ()
    end

    def destroy ()
        @article.destroy
        redirect_to articles_path, status: :see_other
    end

    # solo usado dentro de este controlador
    private
    
    def set_article 
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin
            flash[:alert] = "You can only edit or delete your own article"
            redirect_to @article
        end
    end
end

udemy/projects/alpha-blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was created successfully"
            redirect_to category_path(@category)
        else
            render 'new'
        end
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category was updated successfully"
            redirect_to category_path(@category)
        else
            render 'edit'
        end
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can do that action"
            redirect_to categories_path
        end
    end

end

udemy/projects/alpha-blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home ()
        redirect_to articles_path if logged_in?
    end

    def about()
    end
end

udemy/projects/alpha-blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)

        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged successfully"
            redirect_to user
        else
            flash.now[:alert] = "There was something wrong with your login details"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "You have logged out successfully"
        redirect_to root_path
    end
end

udemy/projects/alpha-blog/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new (user_params)
        if @user.save
            flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully sign up"
            session[:user_id] = @user.id
            redirect_to articles_path
        else 
            render 'new'
        end
    end

    def edit 
    end

    def update
        if (@user.update(user_params))
            flash[:notice] = "Your account information was successfully updated"
            redirect_to @user
        else
            render 'edit'
        end
    end

    def show
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def index 
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def destroy 
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "User accout deleted"
        redirect_to root_path
    end



    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find params[:id]
    end

    def require_same_user
        if current_user != @user && !current_user.admin
            flash[:alert] = "You can only edit your own profile"
            redirect_to @user
        end
    end
end

udemy/projects/alpha-blog/app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for (user, options = {size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        return image_tag(image_src, alt: user.username, class: "rounded shadow mx-auto d-block")
    end

end

udemy/projects/alpha-blog/app/helpers/pages_helper.rb
module PagesHelper
end

udemy/projects/alpha-blog/app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article|%>
    <div class="row justify-content-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              By: <%= link_to article.user.username, user_path(article.user) %>
            <% end %>

            <%if article.categories.any? %>
              <div class="mt-3">
                <%= render article.categories %>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-success" %>

            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-info" %>
              <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Do you really want to delete"}, class: "btn btn-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at)%> ago, 
            edited <%= time_ago_in_words(article.updated_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

udemy/projects/alpha-blog/app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @article%>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
            { prompt: "Make your selection from the list below" }, { multiple: true, size: 3, class: 'custom-select shadow rounded' }) %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

udemy/projects/alpha-blog/app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit Article</h1>

<%= render 'form'%>

udemy/projects/alpha-blog/app/views/articles/index.html.erb
<h1 class="text-center mt-4">Article Index</h1>

<div class="flickr_pagination mt-3">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render "article"%>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

udemy/projects/alpha-blog/app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create Article</h1>
<%= render 'form'%>

udemy/projects/alpha-blog/app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container">
    <div class="row justify-content-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            By: <%= @article.user.username if @article.user%>
            <%= link_to gravatar_for(@article.user), user_path(@article.user)%>
            <%if @article.categories.any? %>
              <div class="mt-3">
                <%= render @article.categories %>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <% if logged_in? && (@article.user == current_user || current_user.admin) %>
              <%= link_to "Edit", edit_article_path(@article), class: "btn btn-info" %>
              <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Do you really want to delete"}, class: "btn btn-danger" %>
            <%end%>
          </div>
          <div class="card-footer text-muted">
            <small>Create <%= time_ago_in_words(@article.created_at)%> ago, 
            edited <%= time_ago_in_words(@article.updated_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>
</div>

<p>
</p>

udemy/projects/alpha-blog/app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @user%>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter email" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

udemy/projects/alpha-blog/app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form'%>

udemy/projects/alpha-blog/app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="flickr_pagination mt-3">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user|%>
    <div class="row justify-content-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            By: <%= link_to user.username, user_path(user) %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
                <%= link_to gravatar_for(user, size: 150), user_path(user) %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user_path(user), class: "btn btn-success" %>
            <% if logged_in? %>
              <% if user == current_user%>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-info" %>
              <% end %>
              <% if current_user.admin %>
                <%= link_to "Delete profile", user_path(user), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure ? "} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @users, :container => false %>
</div>

udemy/projects/alpha-blog/app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>
<%= render 'form'%>

udemy/projects/alpha-blog/app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %></h1>

<%= gravatar_for @user, size: 200 %>

<div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path, class: "btn btn-info" %>
</div>

<h3 class="text-center mt-4">Articles</h3>

<%= render "articles/article"%>